DROP TABLE `accessibility_audits`;--> statement-breakpoint
DROP TABLE `api_endpoints`;--> statement-breakpoint
DROP TABLE `case_studies`;--> statement-breakpoint
DROP TABLE `client_contacts`;--> statement-breakpoint
DROP TABLE `email_logs`;--> statement-breakpoint
DROP TABLE `email_templates`;--> statement-breakpoint
DROP TABLE `environment_configs`;--> statement-breakpoint
DROP TABLE `estimations`;--> statement-breakpoint
DROP TABLE `feasibility_checks`;--> statement-breakpoint
DROP TABLE `feedback_items`;--> statement-breakpoint
DROP TABLE `integrations`;--> statement-breakpoint
DROP TABLE `invoice_items`;--> statement-breakpoint
DROP TABLE `invoices`;--> statement-breakpoint
DROP TABLE `lead_scoring_rules`;--> statement-breakpoint
DROP TABLE `lead_tags`;--> statement-breakpoint
DROP TABLE `lessons_learned`;--> statement-breakpoint
DROP TABLE `maintenance_tasks`;--> statement-breakpoint
DROP TABLE `meeting_notes`;--> statement-breakpoint
DROP TABLE `meetings`;--> statement-breakpoint
DROP TABLE `mobile_checks`;--> statement-breakpoint
DROP TABLE `nps_surveys`;--> statement-breakpoint
DROP TABLE `payments`;--> statement-breakpoint
DROP TABLE `performance_tests`;--> statement-breakpoint
DROP TABLE `process_suggestions`;--> statement-breakpoint
DROP TABLE `qa_signoffs`;--> statement-breakpoint
DROP TABLE `retrospectives`;--> statement-breakpoint
DROP TABLE `risk_assessments`;--> statement-breakpoint
DROP TABLE `security_audits`;--> statement-breakpoint
DROP TABLE `stakeholders`;--> statement-breakpoint
DROP TABLE `sub_tasks`;--> statement-breakpoint
DROP TABLE `support_tickets`;--> statement-breakpoint
DROP TABLE `system_health`;--> statement-breakpoint
DROP TABLE `task_checklists`;--> statement-breakpoint
DROP TABLE `time_entries`;--> statement-breakpoint
DROP TABLE `webhook_deliveries`;--> statement-breakpoint
ALTER TABLE `users` ADD `status` text DEFAULT 'pending' NOT NULL;